# Cloudflare Worker 配置文件
# 参考文档: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "gamechi-auto-renew" # Worker 的名称
main = "index.js"          # 入口文件
compatibility_date = "2023-08-01" # 兼容性日期，确保 API 行为一致性
