# Cloudflare Worker 配置文件
# 参考文档: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "gamechi-auto-renew" # Worker 的名称
main = "dist/worker.js"          # 入口文件
compatibility_date = "2023-08-01" # 兼容性日期，确保 API 行为一致性

# =================================================================================
# KV 命名空间绑定
# =================================================================================
# 注意: 在首次部署 (npx wrangler deploy) 前，您需要运行以下命令来创建一个 KV 命名空间:
# npx wrangler kv:namespace create "AUTO_RENEW_KV"
#
# 然后将生成的 id 填充到下面的配置中。
# =================================================================================
kv_namespaces = [
  { binding = "AUTO_RENEW_KV", id = "在此处填入您创建的KV命名空间的ID" } # 用于存储服务器配置
]
